# Generated by Django 5.1.1 on 2026-03-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
